Nodes.Guru Kyve support
eco-stake/validator-registry pull request #2307
Opened 2023-03-14 22:35 UTC by kinrokinro

2023-03-14 23:32 UTC, tombeynon requested changes

2023-03-14 23:32 UTC, tombeynon commented on nodesguru/chains.json
> +        "run_time": "every 24 hours",
This should be a time if it's daily, e.g 00:00 or 09:00

2023-03-14 23:47 UTC, kinrokinro commented
@tombeynon done

2023-03-15 00:08 UTC, tombeynon approved these changes

2023-03-15 00:08 UTC, merged