Update chains.json
eco-stake/validator-registry pull request #2637
Opened 2023-04-29 13:45 UTC by staking-hub

2023-04-30 11:09 UTC, tombeynon requested changes

2023-04-30 11:09 UTC, tombeynon commented on stakershub/chains.json
> + //  {
I'm afraid JSON doesn't support comments so you'll need to remove this section

2023-05-02 20:55 UTC, staking-hub commented
Ok sorry I didn't know so I remove the whole reference

2023-05-03 10:58 UTC, tombeynon approved these changes

2023-05-03 10:58 UTC, merged