NG upd Agoric run_time
eco-stake/validator-registry pull request #760
Opened 2022-08-17 11:32 UTC by kinrokinro

2022-08-17 12:44 UTC, tombeynon requested changes

2022-08-17 12:44 UTC, tombeynon commented on nodesguru/chains.json
> +        "run_time": "daily",
You need to specify the time in UTC for daily - e.g. `"run_time": "21:00"`

2022-08-24 11:18 UTC, tombeynon commented
@kinrokinro closing this for now, reopen when you're ready

2022-08-24 11:18 UTC, closed without merging

2022-08-24 11:48 UTC, kinrokinro commented
@tombeynon https://github.com/eco-stake/validator-registry/pull/819