Added Galaxy - Evmos
eco-stake/validator-registry pull request #905
Opened 2022-09-09 14:53 UTC by dwgalaxydigital

2022-09-09 16:51 UTC, gh0stdotexe commented
> _ No description provided. _

Looks like you used your ETH address for REStake, please use the Cosmos ecosystem EVMOS address for your REStake wallet, please :)

2022-09-10 14:08 UTC, tombeynon requested changes
See gh0sts comment

2022-09-12 14:10 UTC, dwgalaxydigital commented
> See gh0sts comment

Updated. Thanks, guys.

2022-09-12 14:12 UTC, tombeynon approved these changes

2022-09-12 14:12 UTC, merged